name: restaurant_menu
description: "Restaurant App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  http: ^1.1.0
  modal_bottom_sheet: ^3.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
